### ISSUE TITLE
where is serial_util.py?

### ISSUE THREAD

**Issue by skywo1f** [omnipresense/OPS241A_RasPiLCD#5]
radar restarter calls for it, but I cant find it anywhere in the repo

**Comment by omnipresense** [comment]
Ah, Hi, yes, it's in 
https://github.com/omnipresense/python_utilities

The "requirement/dependency" was to try and get over a related problem that the average person will not experience, so I'll comment it out of radar_restarter

**Comment by omnipresense** [comment]
Here is the latest advice on avoiding the problem.
https://omnipresense.github.io/knowledge-base/USB_issues#about-debianraspbianubuntus-undesired-line-echo-behavior

(and in the intervening years, we've made our sensor more resilient to having its output returned as input)

**Comment by skywo1f** [comment]
thanks!
